:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 25
:verbose: false
:queues:
  - [default, 5]
  - [mailers, 3]
  - [low, 1]

:scheduler:
  :enabled: true
  :dynamic: false

development:
  :concurrency: 3

production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
  :logfile: ./log/sidekiq.log

test:
  :concurrency: 1
  :verbose: true
