version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-recomeshi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-recomeshi_password}
      POSTGRES_DB: ${POSTGRES_DB:-recomeshi_development}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - rails_bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-recomeshi}:${POSTGRES_PASSWORD:-recomeshi_password}@postgres:5432/${POSTGRES_DB:-recomeshi_development}
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api/v1}
      VITE_CONFIRMABLE_ENABLED: ${VITE_CONFIRMABLE_ENABLED:-false}
    stdin_open: true
    tty: true

  liff:
    build:
      context: ./liff
      dockerfile: Dockerfile.dev
    volumes:
      - ./liff:/app
      - liff_node_modules:/app/node_modules
    ports:
      - "3002:3002"
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
      VITE_LIFF_ID: ${VITE_LIFF_ID}
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:
  rails_bundle:
  node_modules:
  liff_node_modules: