FROM ruby:3.2.0

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
  postgresql-client \
  build-essential \
  libpq-dev \
  nodejs \
  npm \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Rails
RUN gem install rails -v '~> 7.2.0'

# Create app directory
WORKDIR /app

# Create entrypoint script
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# Expose port
EXPOSE 3000

# Start the main process
CMD ["rails", "server", "-b", "0.0.0.0"]