# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

# 拡充された食材マスタデータを作成
ingredients_data = [
  # 野菜類（根菜）
  { name: 'にんじん', category: 'vegetables', unit: '本', emoji: '🥕' },
  { name: '人参', category: 'vegetables', unit: '本', emoji: '🥕' },
  { name: 'じゃがいも', category: 'vegetables', unit: '個', emoji: '🥔' },
  { name: '玉ねぎ', category: 'vegetables', unit: '個', emoji: '🧅' },
  { name: '長ねぎ', category: 'vegetables', unit: '本', emoji: '🧅' },
  { name: 'ねぎ', category: 'vegetables', unit: '本', emoji: '🧅' },
  { name: '大根', category: 'vegetables', unit: '本', emoji: '🫗' },
  { name: 'かぶ', category: 'vegetables', unit: '個', emoji: '🫗' },
  { name: 'ごぼう', category: 'vegetables', unit: '本', emoji: '🟤' },
  { name: 'れんこん', category: 'vegetables', unit: '個', emoji: '🟤' },
  { name: 'さつまいも', category: 'vegetables', unit: '本', emoji: '🍠' },
  { name: 'さといも', category: 'vegetables', unit: '個', emoji: '🥔' },
  { name: '里芋', category: 'vegetables', unit: '個', emoji: '🥔' },

  # 野菜類（果菜）
  { name: 'トマト', category: 'vegetables', unit: '個', emoji: '🍅' },
  { name: 'ミニトマト', category: 'vegetables', unit: 'パック', emoji: '🍅' },
  { name: 'プチトマト', category: 'vegetables', unit: 'パック', emoji: '🍅' },
  { name: 'きゅうり', category: 'vegetables', unit: '本', emoji: '🥒' },
  { name: 'なす', category: 'vegetables', unit: '本', emoji: '🍆' },
  { name: 'ピーマン', category: 'vegetables', unit: '個', emoji: '🫑' },
  { name: 'パプリカ', category: 'vegetables', unit: '個', emoji: '🫑' },
  { name: 'ししとう', category: 'vegetables', unit: 'パック', emoji: '🌶️' },
  { name: 'オクラ', category: 'vegetables', unit: 'パック', emoji: '🌶️' },
  { name: 'いんげん', category: 'vegetables', unit: 'パック', emoji: '🫛' },
  { name: 'えだまめ', category: 'vegetables', unit: 'パック', emoji: '🫛' },
  { name: '枝豆', category: 'vegetables', unit: 'パック', emoji: '🫛' },
  { name: 'かぼちゃ', category: 'vegetables', unit: '個', emoji: '🎃' },
  { name: 'ズッキーニ', category: 'vegetables', unit: '本', emoji: '🥒' },
  { name: 'とうもろこし', category: 'vegetables', unit: '本', emoji: '🌽' },

  # 野菜類（葉菜）
  { name: 'キャベツ', category: 'vegetables', unit: '個', emoji: '🥬' },
  { name: 'レタス', category: 'vegetables', unit: '個', emoji: '🥬' },
  { name: 'サニーレタス', category: 'vegetables', unit: '個', emoji: '🥬' },
  { name: 'ほうれん草', category: 'vegetables', unit: '束', emoji: '🥬' },
  { name: '小松菜', category: 'vegetables', unit: '束', emoji: '🥬' },
  { name: 'チンゲン菜', category: 'vegetables', unit: '株', emoji: '🥬' },
  { name: '青梗菜', category: 'vegetables', unit: '株', emoji: '🥬' },
  { name: '白菜', category: 'vegetables', unit: '個', emoji: '🥬' },
  { name: 'もやし', category: 'vegetables', unit: '袋', emoji: '🌱' },
  { name: '水菜', category: 'vegetables', unit: '袋', emoji: '🥬' },
  { name: '春菊', category: 'vegetables', unit: '束', emoji: '🥬' },
  { name: '大葉', category: 'vegetables', unit: 'パック', emoji: '🌿' },
  { name: 'しそ', category: 'vegetables', unit: 'パック', emoji: '🌿' },
  { name: 'パセリ', category: 'vegetables', unit: 'パック', emoji: '🌿' },
  { name: 'セロリ', category: 'vegetables', unit: '本', emoji: '🥬' },

  # 野菜類（きのこ）
  { name: 'しいたけ', category: 'vegetables', unit: 'パック', emoji: '🍄' },
  { name: 'えのき', category: 'vegetables', unit: 'パック', emoji: '🍄' },
  { name: 'えのきたけ', category: 'vegetables', unit: 'パック', emoji: '🍄' },
  { name: 'しめじ', category: 'vegetables', unit: 'パック', emoji: '🍄' },
  { name: 'エリンギ', category: 'vegetables', unit: 'パック', emoji: '🍄' },
  { name: 'まいたけ', category: 'vegetables', unit: 'パック', emoji: '🍄' },
  { name: 'なめこ', category: 'vegetables', unit: 'パック', emoji: '🍄' },

  # 野菜類（その他）
  { name: 'ブロッコリー', category: 'vegetables', unit: '個', emoji: '🥦' },
  { name: 'カリフラワー', category: 'vegetables', unit: '個', emoji: '🥦' },
  { name: 'アスパラガス', category: 'vegetables', unit: 'パック', emoji: '🟢' },
  { name: 'たけのこ', category: 'vegetables', unit: '本', emoji: '🟤' },
  { name: '筍', category: 'vegetables', unit: '本', emoji: '🟤' },

  # 果物類
  { name: 'りんご', category: 'vegetables', unit: '個', emoji: '🍎' },
  { name: 'バナナ', category: 'vegetables', unit: '本', emoji: '🍌' },
  { name: 'オレンジ', category: 'vegetables', unit: '個', emoji: '🍊' },
  { name: 'みかん', category: 'vegetables', unit: '個', emoji: '🍊' },
  { name: 'レモン', category: 'vegetables', unit: '個', emoji: '🍋' },
  { name: 'ライム', category: 'vegetables', unit: '個', emoji: '🟢' },
  { name: 'グレープフルーツ', category: 'vegetables', unit: '個', emoji: '🍊' },
  { name: 'いちご', category: 'vegetables', unit: 'パック', emoji: '🍓' },
  { name: 'キウイ', category: 'vegetables', unit: '個', emoji: '🥝' },
  { name: 'ぶどう', category: 'vegetables', unit: '房', emoji: '🍇' },
  { name: 'なし', category: 'vegetables', unit: '個', emoji: '🍐' },
  { name: '梨', category: 'vegetables', unit: '個', emoji: '🍐' },
  { name: 'もも', category: 'vegetables', unit: '個', emoji: '🍑' },
  { name: '桃', category: 'vegetables', unit: '個', emoji: '🍑' },

  # 肉類（詳細化）
  { name: '鶏胸肉', category: 'meat', unit: 'g', emoji: '🍗' },
  { name: '鶏もも肉', category: 'meat', unit: 'g', emoji: '🍗' },
  { name: '鶏ささみ', category: 'meat', unit: 'g', emoji: '🍗' },
  { name: '手羽先', category: 'meat', unit: '本', emoji: '🍗' },
  { name: '手羽元', category: 'meat', unit: '本', emoji: '🍗' },
  { name: '豚こま切れ肉', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '豚バラ肉', category: 'meat', unit: 'g', emoji: '🥓' },
  { name: '豚ロース', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '豚肩ロース', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '牛こま切れ肉', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '牛バラ肉', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '牛ステーキ肉', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '牛切り落とし', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: '鶏ひき肉', category: 'meat', unit: 'g', emoji: '🍗' },
  { name: '豚ひき肉', category: 'meat', unit: 'g', emoji: '🐷' },
  { name: '牛ひき肉', category: 'meat', unit: 'g', emoji: '🐄' },
  { name: '合いびき肉', category: 'meat', unit: 'g', emoji: '🥩' },
  { name: 'ベーコン', category: 'meat', unit: 'g', emoji: '🥓' },
  { name: 'ハム', category: 'meat', unit: '枚', emoji: '🍖' },
  { name: 'ソーセージ', category: 'meat', unit: '本', emoji: '🌭' },
  { name: 'ウインナー', category: 'meat', unit: '本', emoji: '🌭' },

  # 魚介類（詳細化）
  { name: '鮭', category: 'fish', unit: '切', emoji: '🐟' },
  { name: 'サーモン', category: 'fish', unit: '切', emoji: '🐟' },
  { name: 'まぐろ', category: 'fish', unit: 'g', emoji: '🐟' },
  { name: 'さば', category: 'fish', unit: '尾', emoji: '🐟' },
  { name: 'いわし', category: 'fish', unit: '尾', emoji: '🐟' },
  { name: 'ぶり', category: 'fish', unit: '切', emoji: '🐟' },
  { name: 'あじ', category: 'fish', unit: '尾', emoji: '🐟' },
  { name: 'さんま', category: 'fish', unit: '尾', emoji: '🐟' },
  { name: 'いか', category: 'fish', unit: '杯', emoji: '🦑' },
  { name: 'えび', category: 'fish', unit: '尾', emoji: '🦐' },
  { name: 'エビ', category: 'fish', unit: '尾', emoji: '🦐' },
  { name: 'かに', category: 'fish', unit: '杯', emoji: '🦀' },
  { name: 'カニ', category: 'fish', unit: '杯', emoji: '🦀' },
  { name: 'たこ', category: 'fish', unit: 'g', emoji: '🐙' },
  { name: 'タコ', category: 'fish', unit: 'g', emoji: '🐙' },
  { name: 'ほたて', category: 'fish', unit: '個', emoji: '🦪' },
  { name: 'ホタテ', category: 'fish', unit: '個', emoji: '🦪' },
  { name: 'あさり', category: 'fish', unit: 'g', emoji: '🦪' },
  { name: 'しじみ', category: 'fish', unit: 'g', emoji: '🦪' },

  # 乳製品・卵類（詳細化）
  { name: '牛乳', category: 'dairy', unit: 'ml', emoji: '🥛' },
  { name: '低脂肪乳', category: 'dairy', unit: 'ml', emoji: '🥛' },
  { name: '豆乳', category: 'dairy', unit: 'ml', emoji: '🥛' },
  { name: 'チーズ', category: 'dairy', unit: 'g', emoji: '🧀' },
  { name: 'プロセスチーズ', category: 'dairy', unit: '個', emoji: '🧀' },
  { name: 'クリームチーズ', category: 'dairy', unit: 'g', emoji: '🧀' },
  { name: 'カッテージチーズ', category: 'dairy', unit: 'g', emoji: '🧀' },
  { name: 'ヨーグルト', category: 'dairy', unit: 'g', emoji: '🥛' },
  { name: 'バター', category: 'dairy', unit: 'g', emoji: '🧈' },
  { name: 'マーガリン', category: 'dairy', unit: 'g', emoji: '🧈' },
  { name: '生クリーム', category: 'dairy', unit: 'ml', emoji: '🥛' },
  { name: 'サワークリーム', category: 'dairy', unit: 'g', emoji: '🥛' },
  { name: '卵', category: 'dairy', unit: '個', emoji: '🥚' },
  { name: 'たまご', category: 'dairy', unit: '個', emoji: '🥚' },
  { name: 'うずらの卵', category: 'dairy', unit: '個', emoji: '🥚' },

  # 調味料・香辛料（詳細化）
  { name: '醤油', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: '薄口醤油', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: 'みりん', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: '料理酒', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: '日本酒', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: '塩', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: 'こしょう', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: 'コショウ', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: '砂糖', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: '上白糖', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: 'きび砂糖', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: '三温糖', category: 'seasonings', unit: 'g', emoji: '🧂' },
  { name: '味噌', category: 'seasonings', unit: 'g', emoji: '🍜' },
  { name: '白味噌', category: 'seasonings', unit: 'g', emoji: '🍜' },
  { name: '赤味噌', category: 'seasonings', unit: 'g', emoji: '🍜' },
  { name: 'サラダ油', category: 'seasonings', unit: 'ml', emoji: '🫗' },
  { name: 'オリーブ油', category: 'seasonings', unit: 'ml', emoji: '🫗' },
  { name: 'オリーブオイル', category: 'seasonings', unit: 'ml', emoji: '🫗' },
  { name: 'ごま油', category: 'seasonings', unit: 'ml', emoji: '🫗' },
  { name: '酢', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: '米酢', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: 'ポン酢', category: 'seasonings', unit: 'ml', emoji: '🍶' },
  { name: 'マヨネーズ', category: 'seasonings', unit: 'g', emoji: '🥫' },
  { name: 'ケチャップ', category: 'seasonings', unit: 'g', emoji: '🥫' },
  { name: 'ソース', category: 'seasonings', unit: 'ml', emoji: '🥫' },
  { name: 'ウスターソース', category: 'seasonings', unit: 'ml', emoji: '🥫' },
  { name: '中濃ソース', category: 'seasonings', unit: 'ml', emoji: '🥫' },
  { name: 'とんかつソース', category: 'seasonings', unit: 'ml', emoji: '🥫' },
  { name: 'めんつゆ', category: 'seasonings', unit: 'ml', emoji: '🍜' },
  { name: 'だし', category: 'seasonings', unit: 'g', emoji: '🍜' },
  { name: 'だしの素', category: 'seasonings', unit: 'g', emoji: '🍜' },
  { name: 'コンソメ', category: 'seasonings', unit: '個', emoji: '🧂' },
  { name: 'にんにく', category: 'seasonings', unit: '片', emoji: '🧄' },
  { name: 'しょうが', category: 'seasonings', unit: 'g', emoji: '🫚' },
  { name: '生姜', category: 'seasonings', unit: 'g', emoji: '🫚' },

  # 主食・麺類・パン類
  { name: '米', category: 'others', unit: 'g', emoji: '🍚' },
  { name: '白米', category: 'others', unit: 'g', emoji: '🍚' },
  { name: '玄米', category: 'others', unit: 'g', emoji: '🍚' },
  { name: 'もち米', category: 'others', unit: 'g', emoji: '🍚' },
  { name: '食パン', category: 'others', unit: '枚', emoji: '🍞' },
  { name: 'フランスパン', category: 'others', unit: 'g', emoji: '🥖' },
  { name: 'ロールパン', category: 'others', unit: '個', emoji: '🍞' },
  { name: 'うどん', category: 'others', unit: '玉', emoji: '🍜' },
  { name: 'そば', category: 'others', unit: '束', emoji: '🍜' },
  { name: 'そうめん', category: 'others', unit: '束', emoji: '🍜' },
  { name: 'パスタ', category: 'others', unit: 'g', emoji: '🍝' },
  { name: 'スパゲッティ', category: 'others', unit: 'g', emoji: '🍝' },
  { name: 'ラーメン', category: 'others', unit: '玉', emoji: '🍜' },
  { name: '中華麺', category: 'others', unit: '玉', emoji: '🍜' },
  { name: '春雨', category: 'others', unit: 'g', emoji: '🍜' },

  # 豆類・豆製品
  { name: '豆腐', category: 'others', unit: '丁', emoji: '⬜' },
  { name: '絹ごし豆腐', category: 'others', unit: '丁', emoji: '⬜' },
  { name: '木綿豆腐', category: 'others', unit: '丁', emoji: '⬜' },
  { name: '厚揚げ', category: 'others', unit: '個', emoji: '🟫' },
  { name: '油揚げ', category: 'others', unit: '枚', emoji: '🟫' },
  { name: '納豆', category: 'others', unit: 'パック', emoji: '🫘' },
  { name: '大豆', category: 'others', unit: 'g', emoji: '🫘' },
  { name: '小豆', category: 'others', unit: 'g', emoji: '🫘' },
  { name: 'いんげん豆', category: 'others', unit: 'g', emoji: '🫘' },

  # 冷凍食品
  { name: '冷凍野菜', category: 'others', unit: 'g', emoji: '❄️' },
  { name: '冷凍ほうれん草', category: 'others', unit: 'g', emoji: '❄️' },
  { name: '冷凍ブロッコリー', category: 'others', unit: 'g', emoji: '❄️' },
  { name: '冷凍コーン', category: 'others', unit: 'g', emoji: '❄️' },
  { name: '冷凍えび', category: 'others', unit: 'g', emoji: '❄️' },
  { name: '冷凍餃子', category: 'others', unit: '個', emoji: '❄️' },

  # その他
  { name: '海苔', category: 'others', unit: '枚', emoji: '🟫' },
  { name: 'わかめ', category: 'others', unit: 'g', emoji: '🟢' },
  { name: '昆布', category: 'others', unit: 'g', emoji: '🟫' },
  { name: 'ひじき', category: 'others', unit: 'g', emoji: '🟫' },
  { name: 'ごま', category: 'others', unit: 'g', emoji: '⚪' },
  { name: '白ごま', category: 'others', unit: 'g', emoji: '⚪' },
  { name: '黒ごま', category: 'others', unit: 'g', emoji: '⚫' },
  { name: 'パン粉', category: 'others', unit: 'g', emoji: '🟫' },
  { name: '小麦粉', category: 'others', unit: 'g', emoji: '⚪' },
  { name: '片栗粉', category: 'others', unit: 'g', emoji: '⚪' }
]

puts '食材マスタデータを作成中...'

ingredients_data.each do |ingredient_data|
  ingredient = Ingredient.find_or_create_by!(name: ingredient_data[:name]) do |i|
    i.category = ingredient_data[:category]
    i.unit = ingredient_data[:unit]
    i.emoji = ingredient_data[:emoji]
  end

  puts "✓ #{ingredient.display_name_with_emoji} (#{ingredient.category})"
end

puts "食材マスタデータの作成完了！ 合計: #{Ingredient.count}件"
